### PR TITLE
Updating GraphQL and REST API schemas for 2.4.6

### PR DESCRIPTION
**Pull request by jhadobe**
This PR updates the GraphQL and REST schemas as part of the post-release tasks.

The REST schemas require additional work in Redocly.

I did not replace `null` description fields yet in the GraphQL schema, it appeared to build correctly (locally). I will re-add the "no description" descriptions if it errors in staging. 

I would like to leave the `2.4.5` schema files in place for now and remove them in a future PR.

Internal tracking: COMDOX-410 and COMDOX-493.

### Staging sites

- developer.adobe.com reference site (GraphQL)
  - https://developer-stage.adobe.com/commerce/webapi/graphql/reference/
- redoc stage (REST)
  - https://adobe-commerce-stage.redoc.ly/

### Sanity check in files (via diff checking)

These are the main additions I saw when comparing `2.4.5` to `2.4.6`

- Admin 
  - Quick Checkout
  - `bolt_id` added to `quote-data-address-extension-interface:`
  - `import-csv-api-data-source-data-interface`
  - `quick-checkout-data-account-interface`
  - `adobe_io_events/check_configuration`
  - `adobe_io_events/check_configuration`
  - `analytics-data-link-interface`
- Customer
  - Quick Checkout
  - `bolt_id` added to `quote-data-address-extension-interface:`
  - `/V1/integration/customer/revoke-customer-token`
- Guest
  - Quick Checkout
  - `bolt_id` added to `quote-data-address-extension-interface:`

### CODE REVIEW

**Review by jeff-matthews — COMMENTED** [review]
I checked the GraphQL reference on staging and didn't see any problems. Specifically, I looked for small text and broken styling that we thought was caused by null description fields. So that looks good.

I recognize the import CSV addition in the REST schema, so I suspect that's correct. Will you be providing staging links for Redocly as described in the internal wiki?

**Comment by dshevtsov** [comment]
I recommend splitting the REST and GraphQL updates into two PRs in the future.
Also, I removed links to internal resources in the PR description because we have a convention to avoid using any links to internal resources in public PRs.

**Comment by dshevtsov** [comment]
I changed status of the PR to draft because of `Staging site (coming soon)` phrase.

**Review by jeff-matthews — APPROVED** [review]
Nice! Thanks @jhadobe.

I see B2B endpoints (like negotiable quote) as expected in the admin schema. The review approval criteria in the internal wiki says that the customer schema should contain negotiable quote endpoints as well, but I only see negotiable cart. Since the wiki has been somewhat unreliable and outdated this release, I don't think it should block merging. 

I think we need to create a more formal/codified list of review/approval criteria, which we can't do until @keharper gets back. I like the approach you chose with highlighting items from a diff in the PR description though.

**Comment by jhadobe** [comment]
> I see B2B endpoints (like negotiable quote) as expected in the admin schema. The review approval criteria in the internal wiki says that the customer schema should contain negotiable quote endpoints as well, but I only see negotiable cart. 

In the Customer schemas, I ran a quick test and it appears the `2.4.5` and `2.4.6` versions have the same amount of occurrences of "negotiable-quote" (28).

**Comment by jeff-matthews** [comment]
Interesting... I used the Redocly search and didn't see negotiable quote at all for the customer schema.

**Review by dshevtsov — CHANGES_REQUESTED** [review]
GraphQL API version wasn't updated

Screenshot 2023-03-15 at 6 27 19 PM

**Comment by jhadobe** [comment]
> GraphQL API version wasn't updated

Good catch, @dshevtsov. It looks like the SpectaQL command didn't run properly the first time. I'm redploying to stage, it should be live in ~20 minutes.

**Review by dshevtsov — APPROVED** [review]

**Comment by jhadobe** [comment]
> Interesting... I used the Redocly search and didn't see negotiable quote at all for the customer schema.

To clarify, I mean that the number of occurrences are the same. I.e. it does not appear as an endpoint in the `2.4.5` Customer schema either: https://adobe-commerce.redoc.ly/2.4.5-customer/

**Pull request merged**
