### PR TITLE
Add a remark plugin to support custom header id

### PR DESCRIPTION
**Pull request by dshevtsov**
## Purpose of this pull request

This pull request (PR) adds a [remark-heading-id](https://github.com/imcuttle/remark-heading-id) plugin that allows validation of custom headers via remark-validate-links.

## Test

See https://github.com/AdobeDocs/commerce-admin-developer/pull/85

### CODE REVIEW

**Review by jeff-matthews — APPROVED** [review]
Approved for the basic functionality, but I want to note that this repo has special [`--ignore-patterns`](https://github.com/AdobeDocs/commerce-webapi/blob/main/package.json#L31) configured for the `src/_includes` and `src/pages/graphql/schema` directories.

For background, we originally added these patterns because of the false positives with custom header IDs. However, we've since expanded that to ignore frontmatter for the graphql schema directories. I assume we also need to ignore the _includes in the frontmatter checks as well.

Ideally, we would not ignore directories when testing.

**Comment by keharper** [comment]
Coincidentally, in #246 I just deleted nearly 50 schema files that are no longer necessary now that the GraphQL schema docs link directly to SpectaQL. I don't know if it'll be possible to remove the pattern, but the remaining include files probably don't link to other include files.

**Review by keharper — APPROVED** [review]

**Comment by dshevtsov** [comment]
> Approved for the basic functionality, but I want to note that this repo has special [`--ignore-patterns`](https://github.com/AdobeDocs/commerce-webapi/blob/main/package.json#L31) configured for the `src/_includes` and `src/pages/graphql/schema` directories.
> 
> For background, we originally added these patterns because of the false positives with custom header IDs. However, we've since expanded that to ignore frontmatter for the graphql schema directories. I assume we also need to ignore the _includes in the frontmatter checks as well.
> 
> Ideally, we would not ignore directories when testing.

@jeff-matthews please create a ticket for me to investigate the issue.

**Comment by jeff-matthews** [comment]
@dshevtsov, I created #247 that I think will eliminate the need for the `--ignore-patterns` option.

**Pull request merged**
