### PR TITLE
Update CustomizableOptionInput attributes

### PR DESCRIPTION
**Pull request by abukatar**
Changes to reflect functionality added in https://jira.corp.adobe.com/browse/ACP2E-1612

## Description

<p>Update public documentation to reflect changes in the CustomizableOptionInput object</p>
<div class="table-wrap">

`id` | Int | Deprecated. Use `uid` instead. A unique ID assigned to the customizable option
-- | -- | --
`uid` | ID | A unique ID for the `CartItemInterface` object

</div>

## Related Issue
https://github.com/magento-l3/magento2ce/pull/972
https://github.com/magento-l3/magento2ee/pull/283

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ *] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by jhadobe — APPROVED** [review]

**Comment by keharper** [comment]
@abukatar Is this going into the 2.4.7 release? If yes, there's a good chance I'll close this PR. By that point the hand-maintained reference information will be removed from the documentation, in favor of autogenerated documentation. (We're maybe only a few days away from rolling that out.) The code PR doesn't deprecate `CustomizableOptionInput.id`, so it doesn't look like the example in `src/pages/graphql/schema/cart/mutations/add-simple.products.md` doesn't have to be updated.

If this PR is going into 2.4.6, you'll need to rebase the target branch to `2.4.6-develop`. I'll merge the PR, but the content might be deleted by the time 2.4.6 has its public GA (because of the autogenerated content).

**Comment by abukatar** [comment]
Hi @keharper, this is going into 2.4.7. I see your point about the CustomizableOptionInput.id. I'll re-do the implementation and will deprecate it. If the documentation is going to be autogenerated and this piece will be updated automatically, we can close this PR

**Comment by keharper** [comment]
@jeff-matthews No. The [code PR(https://github.com/magento-l3/magento2ce/pull/972) has not been merged. 

Also, @abukatar since you subsequently deprecated `id`, please update the example in src/pages/graphql/schema/cart/mutations/add-simple.products.md

**Comment by jeff-matthews** [comment]
I converted the PR to a draft until we know when the code will be merged.

**Comment by keharper** [comment]
That was a hasty response, trying to head off any premature merging.

@abukatar Back out the change that you created in this PR. The autogenerated docs are live. However, the code sample should still be updated.

**Comment by abukatar** [comment]
@keharper 
Please clarify if we can close the PR since the autogenerated docs are live. The code example on the related page here https://devdocs.magento.com/guides/v2.3/graphql/mutations/update-cart-items.html is still valid and doesn’t have to be updated.

**Comment by keharper** [comment]
OK, if the example doesn't need to be updated, then I'll just go ahead and close this PR.

**Pull request closed without merging**
