### PR TITLE
DEVSITE-685: Move _includes directory to fix duplicate search indexing

### PR DESCRIPTION
**Pull request by jeff-matthews**
## Purpose of this pull request

This pull request (PR) moves the the `src/pages/_includes` directory to `src/_includes/` and updates all references to include files.

The site search indexing process indexes all files under the `src/pages/` directory, which is causing duplicate search results. Instead of adding the new [`noIndex: true`](https://github.com/adobe/aio-theme/tree/%40adobe/gatsby-theme-aio%404.10.5#hide-page-from-search-with-noindex) metadata parameter (aio-theme v4.10.5) to all ~100 include files, this seems like an easier solution.

Local build works as expected and renders include files.

## Staging

- https://developer-stage.adobe.com/commerce/webapi/

### CODE REVIEW

**Comment by jhadobe** [comment]
I've confirmed that the `_includes` folder has been moved up to the `/src` folder. When checking for references to the previous location, all I found was line 28 of the `package.json` file which appears to be a test, which will probably need to be updated as well.

**Comment by jhadobe** [comment]
> I've confirmed that the `_includes` folder has been moved up to the `/src` folder. When checking for references to the previous location, all I found was line 28 of the `package.json` file which appears to be a test, which will probably need to be updated as well.

>     "test:links": "remark src/pages --ignore-pattern src/pages/graphql,src/pages/_includes --quiet --frail",

**Comment by jeff-matthews** [comment]
Good catch @jhadobe! I'll update it.

**Review by jhadobe — APPROVED** [review]
I haven't checked every line, but stage seems fine to me.

**Pull request merged**
