### PR TITLE
COMDOX-782 Fixing nested links

### PR DESCRIPTION
**Pull request by jhadobe**
This PR addresses links opening recursively inside the GraphQL schema. 

This affects the following pages:
- https://developer.adobe.com/commerce/webapi/graphql/reference/
- https://developer.adobe.com/commerce/webapi/graphql/reference/beta/

Redocly preview: https://preview.redoc.ly/nervous-snail-65/jh_spectaql_link/

### CODE REVIEW

**Review by dshevtsov — COMMENTED** [review]
I don't have access to view the preview

**Comment by dshevtsov** [comment]
I'm generating a preview via the GitHub Pages Action

**Comment by dshevtsov** [comment]
GitHub Pages preview: https://adobedocs.github.io/commerce-webapi/graphql/reference/beta/

**Comment by dshevtsov** [comment]
It's not clear what a recursive opening inside schema means. I assume it's the issue when after opening an internal link within iframe, the new window opens within iframe too
Screenshot 2023-09-25 at 12 01 05 PM

**Comment by dshevtsov** [comment]
This issue is still present in the [preview](https://adobedocs.github.io/commerce-webapi/graphql/reference/beta/).
Also, the issue appears only in the [Reference (Beta)](https://developer.adobe.com/commerce/webapi/graphql/reference/beta/) page both at the production and on the preview.

**Comment by jhadobe** [comment]
@dshevtsov I am unable to reproduce the issue in your preview by clicking the link in the intro or from the left nav. Can you specify the steps you are using to recreate the issue?

**Comment by dshevtsov** [comment]
> @dshevtsov I am unable to reproduce the issue in your preview by clicking the link in the intro or from the left nav. Can you specify the steps you are using to recreate the issue?

1. Open Reference (Beta): https://adobedocs.github.io/commerce-webapi/graphql/reference/beta/
1. Click on a hyperlink **GraphQL documentation** at the end of the introduction text.

**Comment by dshevtsov** [comment]
Well, now I cannot reproduce it too. That might've been a cache issue.

**Review by dshevtsov — APPROVED** [review]

**Pull request merged**
