### PR TITLE
Revert "COMDOX-840: Redesign Feedback component"

### PR DESCRIPTION
**Pull request by jeff-matthews**
Reverts AdobeDocs/commerce-webapi#269 so that we can bump the theme and use the native sticky feedback component (#348).

### CODE REVIEW

**Comment by jeff-matthews** [comment]
@dshevtsov, let me know if you want me to also bump the theme in this PR to save time.

**Comment by dshevtsov** [comment]
@jeff-matthews let's keep it split for consistency and transparency.

**Review by dshevtsov — APPROVED** [review]

**Comment by jeff-matthews** [comment]
The production deployment [failed](https://github.com/AdobeDocs/commerce-webapi/actions/runs/10376431834/job/28728387702#step:7:60), but I think that's because I was supposed to update dependencies after removing the shadowed files. The PR to bump the theme should fix it.

**Comment by dshevtsov** [comment]
> The production deployment [failed](https://github.com/AdobeDocs/commerce-webapi/actions/runs/10376431834/job/28728387702#step:7:60), but I think that's because I was supposed to update dependencies after removing the shadowed files.

Then it should've failed during testing.

**Comment by dshevtsov** [comment]
It can be a cache issue. I deleted all caches on GitHub.

**Pull request merged**
