### PR TITLE
COMDOX-856: Remove 2.4.7-beta info

### PR DESCRIPTION
**Pull request by jeff-matthews**
## Purpose of this pull request

This pull request (PR) removes references to 2.4.7-beta (including the REST and GQL API reference) in preparation for the 2.4.7 GA release.

API reference schemas will be updated in a separate PR related to COMDOX-852. The new schemas will replace the 2.4.6 schemas.

### CODE REVIEW

**Comment by jeff-matthews** [comment]
@keharper & @jhadobe 

I just realized that there are some absolute links to the beta GQL docs inside several files:

```
[`customAttributeMetadataV2`](https://developer.adobe.com/commerce/webapi/graphql-api/beta/index.html#query-customAttributeMetadataV2)
```

Is it safe to simply change the URL to the production path? I realize the production path may not exist in some cases, but I would expect it to resolve after @jhadobe updates the schemas for 2.4.7.

**Comment by jhadobe** [comment]
> @keharper & @jhadobe
> 
> I just realized that there are some absolute links to the beta GQL docs inside several files:
> 
> ```
> [`customAttributeMetadataV2`](https://developer.adobe.com/commerce/webapi/graphql-api/beta/index.html#query-customAttributeMetadataV2)
> ```
> 
> Is it safe to simply change the URL to the production path? I realize the production path may not exist in some cases, but I would expect it to resolve after @jhadobe updates the schemas for 2.4.7.

i would assume it would be fine, unless any of the anchors are renamed or removed in the 2.4.7 version. @keharper?

**Review by jhadobe — APPROVED** [review]

**Comment by keharper** [comment]
It will be fine to replace `beta` with a final URL, but doing so will cause link errors.

I would like Jared to generate the 2.4.7 GraphQL schema now-ish using the 2.4-develop branch. This will allow us avoid the linking errors, and it will allow me to add links to the many new queries/mutations that I've processed recently. Then, when the final 2.4.7 image is ready, re-generate the final schema.

**Comment by jeff-matthews** [comment]
Thanks @keharper.

It sounds like we should do that in a separate PR. I won't touch the beta links.

**Pull request merged**
