### PR TITLE
updating schemas

### PR DESCRIPTION
**Pull request by jhadobe**
## Purpose of this pull request

This PR updated the REST and GraphQL schemas to `2.4.7-beta2`.

## Pages affected

- https://developer.adobe.com/commerce/webapi/rest/quick-reference/
- https://developer.adobe.com/commerce/webapi/graphql/reference/beta

## Staging

- GraphQL Beta: https://adobedocs.github.io/commerce-webapi/graphql/reference/beta/
- REST (requires login)
   - Admin - https://preview.redoc.ly/nervous-snail-65/jh_schemas/
   - Guest - https://preview.redoc.ly/tricky-panther-92/jh_schemas/
   - Customer (no changes, did not trigger a preview)

### CODE REVIEW

**Comment by jhadobe** [comment]
# Sanity check

Checking against changelog

## REST

`import/json` - https://github.com/AdobeDocs/commerce-webapi/pull/215/files#diff-1b2a23bf3c01276ca2761e7c8ef22ae79acc726379b7273dcc1b17b89541b316R10677

## GraphQL

`cancelOrder` - https://github.com/AdobeDocs/commerce-webapi/blob/b83c70e01f2125208b01c29b3114b31421d74f1e/spectaql/schema_beta.json#L2079

`attributesForm` - https://github.com/AdobeDocs/commerce-webapi/blob/b83c70e01f2125208b01c29b3114b31421d74f1e/spectaql/schema_beta.json#L17

`attributesList` - https://github.com/AdobeDocs/commerce-webapi/blob/b83c70e01f2125208b01c29b3114b31421d74f1e/spectaql/schema_beta.json#L48

`cart` - https://github.com/AdobeDocs/commerce-webapi/blob/b83c70e01f2125208b01c29b3114b31421d74f1e/spectaql/schema_beta.json#L112

`customAttributeMetadataV2` - https://github.com/AdobeDocs/commerce-webapi/blob/b83c70e01f2125208b01c29b3114b31421d74f1e/spectaql/schema_beta.json#L453C1-L453C1

**Review by dshevtsov — COMMENTED** [review]
@jhadobe please add a link to Pages or Staging preview

**Comment by jhadobe** [comment]
> I love the "Sanity check" comment!
> 
> The only thing that I think needs to be updated is the version in the spectaql config: https://github.com/AdobeDocs/commerce-webapi/blob/main/spectaql/config_beta.yml#L384

updated in latest commit

**Comment by jhadobe** [comment]
> @jhadobe please add a link to Pages or Staging preview

added to description

**Review by dshevtsov — APPROVED** [review]
I don't have access to the preview on redoc.ly. GraphQL looks good.

**Review by keharper — COMMENTED** [review]
Your Sanity Check section means I don't have much to do here. Great job.

**Comment by jhadobe** [comment]
> Strange to see customer schema changes in the file list but that it didn't trigger a preview. But all looks good to me.

Yes, i'm not sure why it isn't triggering, when the other schemas did. i'll double check it once it is published.

**Pull request merged**
