### PR TITLE
Fix indexing

### PR DESCRIPTION
**Pull request by dshevtsov**
## Description

The indexing workflow fails with the following error:

```
warning failed to index to Algolia
error Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:727:3)
    at tryReadSync (node:fs:433:20)
    at readFileSync (node:fs:479:19)
    at getContentFromCache (/home/runner/work/commerce-webapi/commerce-webapi/node_modules/@adobe/gatsby-theme-aio/algolia/helpers/get-content-from-cache.js:29:10)
    at getIFrameContent (/home/runner/work/commerce-webapi/commerce-webapi/node_modules/@adobe/gatsby-theme-aio/algolia/helpers/get-iframe-content.js:34:7)
    at transformer (/home/runner/work/commerce-webapi/commerce-webapi/node_modules/@adobe/gatsby-theme-aio/algolia/index-records.js:84:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at getObjectsMapByQuery (/home/runner/work/commerce-webapi/commerce-webapi/node_modules/gatsby-plugin-algolia/gatsby-node.js:475:20)
    at async Promise.all (index 0)
    at runIndexQueries (/home/runner/work/commerce-webapi/commerce-webapi/node_modules/gatsby-plugin-algolia/gatsby-node.js:1[68](https://github.com/AdobeDocs/commerce-webapi/actions/runs/4297917286/jobs/7491463198#step:7:69):29)
    at Object.exports.onPostBuild (/home/runner/work/commerce-webapi/commerce-webapi/node_modules/gatsby-plugin-algolia/gatsby-node.js:102:21)
    at runAPI (/home/runner/work/commerce-webapi/commerce-webapi/node_modules/gatsby/src/utils/api-runner-node.js:487:16) {
  errno: -21,
  syscall: 'read',
  code: 'EISDIR'
}
```

The issue is caused by the use of link to a directory instead of a file at `frameSrc` in `src/pages/graphql/reference.md`.
Also, upgrading the theme and gatsby dependencies to introduce latest fixes and feature.

## How Has This Been Tested?

[Manual run](https://github.com/AdobeDocs/commerce-webapi/actions/runs/4308176528/jobs/7514135015#step:7:61) of indexing in the dry run mode on the branch with the fix.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by dshevtsov** [comment]
When I remove the `src/pages/graphql/reference.md`, the indexing doesn't fail.

**Review by jeff-matthews — APPROVED** [review]
This is interesting. I was experimenting with the `index.html` file for an unrelated style issue last week (#92).

Have you done a dry-run yet to see how indexing the spectaql-generated page will affect the number of records for this index?

**Comment by dshevtsov** [comment]
> Have you done a dry-run yet to see how indexing the spectaql-generated page will affect the number of records for this index?

With the reference: `info Records to add: 15290`
Without the reference: `info Records to add: 5675`

**Comment by jeff-matthews** [comment]
That's more than I expected, but not a problem. We still have ~560K records left in our plan.

**Pull request merged**
